name: Simple Vercel Deploy

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test --if-present

      - name: Run linter
        run: npm run lint --if-present

      - name: Build project
        run: npm run build --if-present

      - name: Deploy to Vercel (Simple)
        uses: amondnet/vercel-action@v25
        if: github.ref == 'refs/heads/main'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'

      - name: Deployment Summary
        run: |
          echo "🚀 **Deployment Completed!**" >> $GITHUB_STEP_SUMMARY
          echo "✅ Build and tests passed" >> $GITHUB_STEP_SUMMARY
          echo "✅ App deployed to Vercel" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "1. Check your Vercel dashboard for the deployment URL" >> $GITHUB_STEP_SUMMARY
          echo "2. Test the connection button on the deployed app" >> $GITHUB_STEP_SUMMARY
          echo "3. If you see a blank page, the base path fix should resolve it" >> $GITHUB_STEP_SUMMARY
